### ISSUE TITLE
Compatibility issue with Magick.Net 7.4.6

### ISSUE THREAD

**Issue by jackbond** [micjahn/ZXing.Net#117]
I added Magick.NET 7.4.6 to a .netcore 2.1 project which uses ZXing.Net.Bindings.Magick 0.16.5 (which in turn references Magick.NET 7.4.3). I get an array bounds exception with the following code...

```
ZXing.Magick.BarcodeReader reader = new ZXing.Magick.BarcodeReader();

reader.Options.TryHarder = true;

using (MagickImage image = new MagickImage(MagickColor.FromRgb(100, 100, 100), 100, 105))
{
    return reader.Decode(image)?.Text;
}
```

**Comment by micjahn** [comment]
Please post the complete exception with stack trace. Thanks.

**Comment by jackbond** [comment]
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at ZXing.Magick.BarcodeReader.<>c.<.cctor>b__2_0(MagickImage image) in C:\ZXing.Net\Source\Bindings\ZXing.Magick\BarcodeReader.cs:line 31
   at ZXing.BarcodeReader`1.Decode(T barcodeBitmap) in C:\ZXing.Net\Source\lib\BarcodeReaderCustom.cs:line 116
   at DeleteMeCoreTest.UnitTest1.TestMethod1() in c:\temp\DeleteMeCoreTest\DeleteMeCoreTest\UnitTest1.cs:line 23

Minimal unit test solution demonstrating the issue...
[issue.zip](https://github.com/micjahn/ZXing.Net/files/2062786/issue.zip)

**Comment by micjahn** [comment]
It doesn't make sense. But if I compile the ZXing.Magick binding against Magick.Net 7.4.6 the error goes away. Updating the nuget package seems to be the solution.

**Comment by jackbond** [comment]
Yah, it was a strange issue. I was able to workaround it by copying the code for MagickImageLuminanceSource directly into my project, with no changes, and it worked for some reason. Thanks for the fix!
