### ISSUE TITLE
ILMerge fails while merge

### ISSUE THREAD

**Issue by gmorkvenas** [micjahn/ZXing.Net#155]
Hello,

Trying to merge all sample project binaries into one executable:

`"C:\Program Files (x86)\Microsoft\ILMerge\ILMerge.exe" CommandLineDecoder.exe zxing.dll zxing.presentation.dll  /useFullPublicKeyForReferences /out:CommandLineDecoder2.exe`

Got error:
```
An exception occurred during merging:
Unresolved assembly reference not allowed: System.Numerics.
   at System.Compiler.Ir2md.GetAssemblyRefIndex(AssemblyNode assembly)
   at System.Compiler.Ir2md.GetTypeRefIndex(TypeNode type)
   at System.Compiler.Ir2md.VisitReferencedType(TypeNode type)
   at System.Compiler.Ir2md.VisitReferencedType(TypeNode type)
   at System.Compiler.Ir2md.VisitClass(Class Class)
   at System.Compiler.Ir2md.VisitModule(Module module)
   at System.Compiler.Ir2md.SetupMetadataWriter(String debugSymbolsLocation)
   at System.Compiler.Ir2md.WritePE(Module module, String debugSymbolsLocation, BinaryWriter writer)
   at System.Compiler.Writer.WritePE(String location, Boolean writeDebugSymbols, Module module, Boolean delaySign, String keyFileName, String keyName)
   at System.Compiler.Writer.WritePE(CompilerParameters compilerParameters, Module module)
   at ILMerging.ILMerge.Merge()
   at ILMerging.ILMerge.Main(String[] args)
```
Why I'm getting this error? How to fix it?

**Comment by micjahn** [comment]
This one here works for me:
```
"C:\Program Files (x86)\Microsoft\ILMerge\ILMerge.exe" CommandLineDecoder.exe zxing.dll /useFullPublicKeyForReferences /out:CommandLineDecoder2.exe /targetplatform:v4
```
